services:
  - type: web
    name: chatbot-project
    runtime: python
    plan: free
    region: oregon

    buildCommand: "pip install --upgrade pip && pip install -r chatbot_project/requirements.txt"

    startCommand: "python -u -m chatbot_project.app.gradio_app"

    envVars:
      - key: PORT
        value: "10000"