services:
  - type: web
    name: chatbot-project
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install --upgrade pip && pip install -r chatbot_project/requirements.txt"
    startCommand: "python -u -m chatbot_project.app.gradio_app --quick_demo"
    envVars:
      - key: PORT
        value: "10000"
